# GitHub Action Workflow to automatically fetch news daily

name: Daily News Update

on:
  schedule:
    # IMPORTANT: Runs every 3 hours (e.g., at 00:00, 03:00, 06:00 UTC).
    # This keeps the news fresh throughout the day while staying
    # well within the free API limits.
    - cron: '0 */3 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    # Gives the Action permission to write the news.json file to the repository.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch latest news
        run: python news_fetcher.py --api-key ${{ secrets.NEWS_API_KEY }}

      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Automated news update"
          file_pattern: 'news.json'
          commit_user_name: "Automated News Bot"
          commit_user_email: "actions@github.com"
          commit_author: "Automated News Bot <actions@github.com>"

