# GitHub Action Workflow to automatically fetch news daily

name: Daily News Update

on:
  # Triggers the workflow every day at 04:30 UTC, which is 10:00 AM IST.
  schedule:
    - cron: '30 4 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    # --- IMPORTANT FIX: Add this permissions block ---
    # This gives the Action the necessary permission to write the news.json file
    # back to your repository.
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the Python script to fetch news
      - name: Fetch latest news
        run: python news_fetcher.py --api-key ${{ secrets.NEWS_API_KEY }}

      # Step 5: Commit the updated news.json file back to the repository
      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Automated daily news update"
          file_pattern: 'news.json'
          commit_user_name: "Automated News Bot"
          commit_user_email: "actions@github.com"
          commit_author: "Automated News Bot <actions@github.com>"


