# GitHub Action Workflow to automatically fetch news daily

name: Daily News Update

on:
  schedule:
    # Runs every 4 hours. This keeps news fresh and uses API credits efficiently.
    # (6 calls/day for GNews, 6 calls/day for NewsData.io which is 60 credits)
    - cron: '0 */4 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Updated Step: Run the script with BOTH API keys
      - name: Fetch latest news from all sources
        run: python news_fetcher.py --gnews-key ${{ secrets.GNEWS_API_KEY }} --newsdata-key ${{ secrets.NEWSDATA_API_KEY }}

      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Automated news update from multiple sources"
          file_pattern: 'news.json'
          commit_user_name: "Automated News Bot"
          commit_user_email: "actions@github.com"
          commit_author: "Automated News Bot <actions@github.com>"
